config/routes.rb
# frozen_string_literal: true

# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
#
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  get '/health_check', to: 'health_check#all'

  # Error routes.
  match '/401', to: 'errors#unauthorized', via: :all, as: :unauthorized
  match '/404', to: 'errors#not_found', via: :all, as: :not_found
  match '/500', to: 'errors#internal_error', via: :all, as: :internal_error

  # Signin/Signup routes.
  get '/signin', to: 'sessions#signin', as: :signin
  get '/signup', to: 'sessions#new', as: :signup
  post '/signup', to: 'users#create', as: :create_user
  match '/ldap_signin', to: 'sessions#ldap_signin', as: :ldap_signin, via: [:get, :post]

  # Redirect to terms page
  match '/terms', to: 'users#terms', via: [:get, :post]

  # Admin resouces
  resources :admins, only: [:index]

  scope '/admins' do
    # Panel Tabs
    get '/rooms', to: 'admins#server_rooms', as: :admin_rooms
    get '/recordings', to: 'admins#server_recordings', as: :admin_recordings
    get '/site_settings', to: 'admins#site_settings', as: :admin_site_settings
    get '/room_configuration', to: 'admins#room_configuration', as: :admin_room_configuration
    get '/roles', to: 'admins#roles', as: :admin_roles
    # Manage Users
    get '/edit/:user_uid', to: 'admins#edit_user', as: :admin_edit_user
    post '/ban/:user_uid', to: 'admins#ban_user', as: :admin_ban
    post '/unban/:user_uid', to: 'admins#unban_user', as: :admin_unban
    post '/invite', to: 'admins#invite', as: :invite_user
    post '/approve/:user_uid', to: 'admins#approve', as: :admin_approve
    get '/reset', to: 'admins#reset', as: :admin_reset
    post '/undelete', to: 'admins#undelete', as: :admin_undelete
    post '/merge/:user_uid', to: 'admins#merge_user', as: :merge_user
    get '/merge_list', to: 'admins#merge_list', as: :merge_list
    # Site Settings
    post '/update_settings', to: 'admins#update_settings', as: :admin_update_settings
    post '/registration_method', to: 'admins#registration_method', as: :admin_change_registration
    post '/coloring', to: 'admins#coloring', as: :admin_coloring
    post '/clear_cache', to: 'admins#clear_cache', as: :admin_clear_cache
    post '/clear_auth', to: 'admins#clear_auth', as: :admin_clear_auth
    post '/log_level', to: 'admins#log_level', as: :admin_log_level
    # Room Configuration
    post '/update_room_configuration', to: 'admins#update_room_configuration', as: :admin_update_room_configuration
    # Roles
    post '/role', to: 'admins#new_role', as: :admin_new_role
    patch 'roles/order', to: 'admins#change_role_order', as: :admin_roles_order
    post '/role/:role_id', to: 'admins#update_role', as: :admin_update_role
    delete 'role/:role_id', to: 'admins#delete_role', as: :admin_delete_role
  end

  scope '/themes' do
    get '/primary', to: 'themes#index', as: :themes_primary
  end

  # Password reset resources.
  resources :password_resets, only: [:new, :create, :edit, :update]

  # Account activation resources
  scope '/account_activations' do
    get '/', to: 'account_activations#show', as: :account_activation
    get '/edit', to: 'account_activations#edit', as: :edit_account_activation
    post '/resend', to: 'account_activations#resend', as: :resend_email
  end

  # User resources.
  scope '/u' do
    # Handles login of greenlight provider accounts.
    post '/login', to: 'sessions#create', as: :create_session

    # Log the user out of the session.
    post '/logout', to: 'sessions#destroy'

    # Account management.
    get '/:user_uid/edit', to: 'users#edit', as: :edit_user
    get '/:user_uid/change_password', to: 'users#change_password', as: :change_password
    get '/:user_uid/delete_account', to: 'users#delete_account', as: :delete_account
    post '/:user_uid/edit', to: 'users#update', as: :update_user
    post '/:user_uid/change_password', to: 'users#update_password', as: :update_password
    delete '/:user_uid', to: 'users#destroy', as: :delete_user

    # All user recordings
    get '/:user_uid/recordings', to: 'users#recordings', as: :get_user_recordings
  end

  # Handles Omniauth authentication.
  match '/auth/:provider/callback', to: 'sessions#omniauth', via: [:get, :post], as: :omniauth_session
  get '/auth/failure', to: 'sessions#omniauth_fail'
  post '/auth/ldap', to: 'sessions#ldap', as: :ldap_callback

  # Users who can't create rooms
  get '/rooms', to: 'rooms#cant_create_rooms', as: :cant_create_rooms

  # Returns a list of users for the shared access list
  get '/shared_access_list', to: 'users#shared_access_list'

  # Room resources.
  resources :rooms, only: [:create, :show, :destroy], param: :room_uid, path: '/'

  # Join a room by UID
  post '/room/join', to: 'rooms#join_specific_room', as: :join_room

  # Extended room routes.
  scope '/:room_uid' do
    post '/', to: 'rooms#join'
    get '/room_settings', to: 'rooms#room_settings'
    post '/update_settings', to: 'rooms#update_settings'
    get '/current_presentation', to: 'rooms#current_presentation'
    post '/preupload_presentation', to: 'rooms#preupload_presentation'
    post '/remove_presentation', to: 'rooms#remove_presentation'
    post '/update_shared_access', to: 'rooms#shared_access', as: :room_shared_access
    delete '/remove_shared_access', to: 'rooms#remove_shared_access', as: :room_remove_shared_access
    get '/shared_users', to: 'rooms#shared_users', as: :room_shared_users
    post '/start', to: 'rooms#start', as: :start_room
    get '/logout', to: 'rooms#logout', as: :logout_room
    post '/login', to: 'rooms#login', as: :login_room
  end

  # Recording operations routes
  scope '/:meetingID' do
    # Manage recordings
    scope '/:record_id' do
      post '/', to: 'recordings#update', as: :update_recording
      patch '/', to: 'recordings#rename', as: :rename_recording
      delete '/', to: 'recordings#delete', as: :delete_recording
    end
  end

  root to: 'main#index'
end

app/views/shared/_flash_messages.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<% flash.each do |key,value| %>
  <% if key.eql? "success" %>
    <div class="alert alert-success alert-dismissible text-center mb-0">
      <button type="button" class="close" data-dismiss="alert">&times</button>
      <%= value %>
    </div>
  <% elsif key.eql? "alert" %>
    <div class="alert alert-danger alert-dismissible text-center mb-0">
      <button type="button" class="close" data-dismiss="alert">&times</button>
      <%= value %>
    </div>
  <% elsif key.eql? "maintenance" %>
    <div class="alert alert-info alert-dismissible text-center mb-0">
      <%= value %>
      <button id="maintenance-close" type="button" data-date="<%= URI.encode_www_form_component(value).gsub('+', '%20') %>" class="close" data-dismiss="alert">&times</button>
    </div>
  <% elsif key.eql? "info" %>
    <div class="alert alert-info alert-dismissible text-center mb-0">
      <button type="button" class="close" data-dismiss="alert">&times</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<footer class="footer pt-3">
  <p class="text-center mb-1">
    <%= t("footer.powered_by", href: link_to(t("greenlight"), "https://bigbluebutton.org/2018/07/09/greenlight-2-0/", target: "_blank", rel: "noopener")).html_safe %> <%= Greenlight::Application::VERSION %>
    <% if legal_url.present? %>
      <span>
        |
        <%= link_to(t("footer.legal"), legal_url) %>
      </span> 
    <% end %>
    <% if privpolicy_url.present? %>
      <span>
        |
        <%= link_to(t("footer.privpolicy"), privpolicy_url)  %>
      </span>
    <% end %>
  </p>
</footer>

<%= render "shared/components/cookie_warning" %>

app/views/shared/_header.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="header py-4">
  <div class="container">
    <div class="d-flex">
      <%= link_to (current_user ? home_page : root_path), class: "header-brand" do %>
        <% begin %>
          <%= image_tag(logo_image, class: "header-brand-img", alt:"") %>
        <% rescue %>
          <%= t("administrator.site_settings.branding.invalid") %>
        <% end %>
      <% end %>

      <div class="d-flex ml-auto">
        <% if current_user %>

          <%= link_to home_page, class: "px-3 mx-1 mt-1 header-nav #{active_home}" do %>
            <i class="fas fa-home pr-1 "></i><span class="d-none d-sm-inline-block"><%= t("header.dropdown.home") %></span>
          <% end %>

          <% if current_user.role.get_permission("can_create_rooms") && !current_user.has_role?(:super_admin) && !hide_recording_tables %>
            <% all_rec_page = controller_name == "users" && action_name == "recordings" ? "active" : "" %>
            <%= link_to get_user_recordings_path(current_user), class: "px-3 mx-1 mt-1 header-nav #{all_rec_page}" do %>
              <i class="fas fa-video pr-1"></i><span class="d-none d-sm-inline-block"><%= t("header.all_recordings") %></span>
            <% end %>
          <% end %>

          <div class="dropdown">
            <a href="#" class="nav-link pr-0" data-toggle="dropdown">
              <span class="avatar"><%= current_user.name.first %></span>
              <span class="ml-2 d-none d-lg-block">
                <span class="text-default username"><%= current_user.name %></span>
              </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow" x-placement="bottom-end">
              <%= link_to edit_user_path(current_user), class: "dropdown-item"  do %>
                <i class="dropdown-icon fas fa-id-card mr-3"></i><%= t("header.dropdown.settings") %>
              <% end %>
              <% highest_role = current_user.role %>
              <% if highest_role.get_permission("can_manage_users") || highest_role.name == "super_admin" %>
                <%= link_to admins_path, class: "dropdown-item" do %>
                  <i class="dropdown-icon fas fa-user-tie mr-3"></i><%= t("header.dropdown.account_settings") %>
                <% end %>
              <% elsif highest_role.get_permission("can_manage_rooms_recordings")%>
                <%= link_to admin_rooms_path, class: "dropdown-item" do %>
                  <i class="dropdown-icon fas fa-user-tie mr-3"></i><%= t("header.dropdown.account_settings") %>
                <% end %>
              <% elsif highest_role.get_permission("can_edit_site_settings") %>
                <%= link_to admin_site_settings_path, class: "dropdown-item" do %>
                  <i class="dropdown-icon fas fa-user-tie mr-3"></i><%= t("header.dropdown.account_settings") %>
                <% end %>
              <% elsif highest_role.get_permission("can_edit_roles")%>
                <%= link_to admin_roles_path, class: "dropdown-item" do %>
                  <i class="dropdown-icon fas fa-user-tie mr-3"></i><%= t("header.dropdown.account_settings") %>
                <% end %>
              <% end %>
              <div class="dropdown-divider"></div>
              <% if Rails.configuration.help_url.present? %>
                <a class="dropdown-item" href="<%= Rails.configuration.help_url %>" target="_blank" rel="noopener">
                  <i class="dropdown-icon far fa-question-circle"></i> <%= t("header.dropdown.help") %>
                </a>
              <% end %>
              <% if Rails.configuration.report_issue_url.present? %>
                <a class="dropdown-item" href="<%= Rails.configuration.report_issue_url %>" target="_blank" rel="noopener">
                  <i class="dropdown-icon fas fa-exclamation mr-3"></i><%= t("errors.internal.report") %>
                </a>
              <% end %>
              <%= button_to logout_path, class: "dropdown-item" do %>
                <i class="dropdown-icon fas fa-sign-out-alt"></i> <%= t("header.dropdown.signout") %>
              <% end %>
            </div>
          </div>
        <% elsif show_signin %>
          <% allow_greenlight_accounts = allow_greenlight_accounts? %>
          <% if allow_greenlight_accounts %>
            <%= link_to t("login"), signin_path, :class => "btn btn-outline-primary mx-2 sign-in-button" %>
          <% elsif Rails.configuration.loadbalanced_configuration %>
            <%= link_to t("login"), omniauth_login_url(:bn_launcher), :class => "btn btn-outline-primary mx-2 sign-in-button", method: :post %>
          <% else %>
            <%= link_to t("login"), signin_path, :class => "btn btn-outline-primary mx-2 sign-in-button" %>
          <% end %>

          <% if allow_user_signup? && allow_greenlight_accounts %>
            <%= link_to t("signup.title"), signup_path, :class => "btn btn-outline-primary mx-2 sign-in-button" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sessions.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div class="sessions pb-5">
  <div class="container pt-6">

    <%= render "shared/components/subtitle", subtitle: title, search: true %>
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="table-responsive">
            <table id="recordings-table" class="table table-hover table-outline table-vcenter text-nowrap card-table">
              <thead>
                <tr>
                  <th data-header="name" data-order="<%= @order_column == "name" ? @order_direction : "none" %>">
                    <%= t("recording.table.name") %>
                    <% if @order_column == "name" && @order_direction == "desc" %>
                      ↓
                    <% elsif @order_column == "name" && @order_direction == "asc" %>
                      ↑
                    <% end %>
                  </th>
                  <% if recording_thumbnails? %>
                    <th>
                      <%= t("recording.table.thumbnails") %>
                    </th>
                  <% end %>
                  <th class="text-left" data-header="length" data-order="<%= @order_column == "length" ? @order_direction : "none" %>">
                    <%= t("recording.table.length") %>
                    <% if @order_column == "length" && @order_direction == "desc" %>
                      ↓
                    <% elsif @order_column == "length" && @order_direction == "asc" %>
                      ↑
                    <% end %>
                  </th>
                  <th class="text-left" data-header="users" data-order="<%= @order_column == "users" ? @order_direction : "none" %>">
                    <%= t("recording.table.users") %>
                    <% if @order_column == "users" && @order_direction == "desc" %>
                      ↓
                    <% elsif @order_column == "users" && @order_direction == "asc" %>
                      ↑
                    <% end %>
                  </th>
                  <th class="text-left" data-header="visibility" data-order="<%= @order_column == "visibility" ? @order_direction : "none" %>">
                    <%= t("recording.table.visibility") %>
                    <% if @order_column == "visibility" && @order_direction == "desc" %>
                      ↓
                    <% elsif @order_column == "visibility" && @order_direction == "asc" %>
                      ↑
                    <% end %>
                  </th>
                  <th data-header="formats" data-order="<%= @order_column == "formats" ? @order_direction : "none" %>">
                    <%= t("recording.table.formats") %>
                    <% if @order_column == "formats" && @order_direction == "desc" %>
                      ↓
                    <% elsif @order_column == "formats" && @order_direction == "asc" %>
                      ↑
                    <% end %>
                  </th>
                  <% unless only_public %>
                    <th class="text-center"><i class="icon-settings"></i></th>
                  <% end %>
                </tr>
              </thead>
              <tbody id="recording-table">
                <tr id="no_recordings_found" style="display: none;">
                  <td colspan="7" class="text-center h4 p-6 font-weight-normal" >
                    <%= only_public ? t("recording.no_matched_pub_recordings") : t("recording.no_matched_recordings") %>
                  </td>
                </tr>
                <% if recordings.empty? %>
                  <tr>
                    <td colspan="7" class="text-center h4 p-6 font-weight-normal">
                      <% if user_recordings %>
                        <%= t("recording.no_user_recordings") %>
                      <% else %>
                        <%= only_public ? t("recording.no_public_recordings") : t("recording.no_recordings", inject: "") %>
                      <% end %>
                    </td>
                  </tr>
                <% else %>
                  <% failed_recordings = 0 %>
                  <% recordings.each do |recording| %>
                    <% begin %>
                      <% if only_public || (defined?(shared_room) && shared_room) %>
                        <%= render "shared/components/public_recording_row", recording: recording %>
                      <% else %>
                        <%= render "shared/components/recording_row", recording: recording %>
                      <% end %>
                    <% rescue => e %>
                      <% logger.error "Error retrieving recording #{recording[:meetingID]}: #{e} -> #{e.backtrace[0]}" %>
                      <% failed_recordings += 1 %>
                    <% end %>
                  <% end %>

                  <% if failed_recordings > 0 %>
                    <div class="alert alert-danger alert-dismissible text-center mb-0">
                      <%= t("recording.error", count: failed_recordings) %>
                    </div>
                  <% end %>
                <% end %>
              </tbody>
            </table>
            <% if !recordings.empty?%>
              <div class="float-md-right mt-4">
                <%== pagy_bootstrap_nav(pagy) %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render "shared/modals/delete_recording_modal" %> 