config/routes.rb
# frozen_string_literal: true

# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
#
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

Rails.application.routes.draw do
  get '/health_check', to: 'health_check#all'

  # Error routes.
  match '/401', to: 'errors#unauthorized', via: :all, as: :unauthorized
  match '/404', to: 'errors#not_found', via: :all, as: :not_found
  match '/500', to: 'errors#internal_error', via: :all, as: :internal_error

  # Signin/Signup routes.
  get '/signin', to: 'sessions#signin', as: :signin
  get '/signup', to: 'sessions#new', as: :signup
  post '/signup', to: 'users#create', as: :create_user
  match '/ldap_signin', to: 'sessions#ldap_signin', as: :ldap_signin, via: [:get, :post]

  # Redirect to terms page
  match '/terms', to: 'users#terms', via: [:get, :post]

  # Admin resouces
  resources :admins, only: [:index]

  scope '/admins' do
    # Panel Tabs
    get '/rooms', to: 'admins#server_rooms', as: :admin_rooms
    get '/recordings', to: 'admins#server_recordings', as: :admin_recordings
    get '/site_settings', to: 'admins#site_settings', as: :admin_site_settings
    get '/room_configuration', to: 'admins#room_configuration', as: :admin_room_configuration
    get '/roles', to: 'admins#roles', as: :admin_roles
    # Manage Users
    get '/edit/:user_uid', to: 'admins#edit_user', as: :admin_edit_user
    post '/ban/:user_uid', to: 'admins#ban_user', as: :admin_ban
    post '/unban/:user_uid', to: 'admins#unban_user', as: :admin_unban
    post '/invite', to: 'admins#invite', as: :invite_user
    post '/approve/:user_uid', to: 'admins#approve', as: :admin_approve
    get '/reset', to: 'admins#reset', as: :admin_reset
    post '/undelete', to: 'admins#undelete', as: :admin_undelete
    post '/merge/:user_uid', to: 'admins#merge_user', as: :merge_user
    get '/merge_list', to: 'admins#merge_list', as: :merge_list
    # Site Settings
    post '/update_settings', to: 'admins#update_settings', as: :admin_update_settings
    post '/registration_method', to: 'admins#registration_method', as: :admin_change_registration
    post '/coloring', to: 'admins#coloring', as: :admin_coloring
    post '/clear_cache', to: 'admins#clear_cache', as: :admin_clear_cache
    post '/clear_auth', to: 'admins#clear_auth', as: :admin_clear_auth
    post '/log_level', to: 'admins#log_level', as: :admin_log_level
    # Room Configuration
    post '/update_room_configuration', to: 'admins#update_room_configuration', as: :admin_update_room_configuration
    # Roles
    post '/role', to: 'admins#new_role', as: :admin_new_role
    patch 'roles/order', to: 'admins#change_role_order', as: :admin_roles_order
    post '/role/:role_id', to: 'admins#update_role', as: :admin_update_role
    delete 'role/:role_id', to: 'admins#delete_role', as: :admin_delete_role
  end

  scope '/themes' do
    get '/primary', to: 'themes#index', as: :themes_primary
  end

  # Password reset resources.
  resources :password_resets, only: [:new, :create, :edit, :update]

  # Account activation resources
  scope '/account_activations' do
    get '/', to: 'account_activations#show', as: :account_activation
    get '/edit', to: 'account_activations#edit', as: :edit_account_activation
    post '/resend', to: 'account_activations#resend', as: :resend_email
  end

  # User resources.
  scope '/u' do
    # Handles login of greenlight provider accounts.
    post '/login', to: 'sessions#create', as: :create_session

    # Log the user out of the session.
    post '/logout', to: 'sessions#destroy'

    # Account management.
    get '/:user_uid/edit', to: 'users#edit', as: :edit_user
    get '/:user_uid/change_password', to: 'users#change_password', as: :change_password
    get '/:user_uid/delete_account', to: 'users#delete_account', as: :delete_account
    post '/:user_uid/edit', to: 'users#update', as: :update_user
    post '/:user_uid/change_password', to: 'users#update_password', as: :update_password
    delete '/:user_uid', to: 'users#destroy', as: :delete_user

    # All user recordings
    get '/:user_uid/recordings', to: 'users#recordings', as: :get_user_recordings
  end

  # Handles Omniauth authentication.
  match '/auth/:provider/callback', to: 'sessions#omniauth', via: [:get, :post], as: :omniauth_session
  get '/auth/failure', to: 'sessions#omniauth_fail'
  post '/auth/ldap', to: 'sessions#ldap', as: :ldap_callback

  # Users who can't create rooms
  get '/rooms', to: 'rooms#cant_create_rooms', as: :cant_create_rooms

  # Returns a list of users for the shared access list
  get '/shared_access_list', to: 'users#shared_access_list'

  # Room resources.
  resources :rooms, only: [:create, :show, :destroy], param: :room_uid, path: '/'

  # Join a room by UID
  post '/room/join', to: 'rooms#join_specific_room', as: :join_room

  # Extended room routes.
  scope '/:room_uid' do
    post '/', to: 'rooms#join'
    get '/room_settings', to: 'rooms#room_settings'
    post '/update_settings', to: 'rooms#update_settings'
    get '/current_presentation', to: 'rooms#current_presentation'
    post '/preupload_presentation', to: 'rooms#preupload_presentation'
    post '/remove_presentation', to: 'rooms#remove_presentation'
    post '/update_shared_access', to: 'rooms#shared_access', as: :room_shared_access
    delete '/remove_shared_access', to: 'rooms#remove_shared_access', as: :room_remove_shared_access
    get '/shared_users', to: 'rooms#shared_users', as: :room_shared_users
    post '/start', to: 'rooms#start', as: :start_room
    get '/logout', to: 'rooms#logout', as: :logout_room
    post '/login', to: 'rooms#login', as: :login_room
  end

  # Recording operations routes
  scope '/:meetingID' do
    # Manage recordings
    scope '/:record_id' do
      post '/', to: 'recordings#update', as: :update_recording
      patch '/', to: 'recordings#rename', as: :rename_recording
      delete '/', to: 'recordings#delete', as: :delete_recording
    end
  end

  root to: 'main#index'
end

app/models/room.rb
# frozen_string_literal: true

# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
#
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

require 'bbb_api'

class Room < ApplicationRecord
  include Deleteable

  before_create :setup

  before_destroy :destroy_presentation

  validates :name, length: { in: 2..256 }

  belongs_to :owner, class_name: 'User', foreign_key: :user_id
  has_many :shared_access, dependent: :destroy

  has_one_attached :presentation

  class << self
    include Queries

    def admins_search(string)
      like = like_text
      search_query = "rooms.name #{like} :search OR rooms.uid #{like} :search OR users.email #{like} :search" \
      " OR users.#{created_at_text} #{like} :search"

      search_param = "%#{sanitize_sql_like(string)}%"
      where(search_query, search: search_param)
    end

    def admins_order(column, direction, running_ids)
      # Include the owner of the table
      table = joins(:owner)

      # Rely on manual ordering if trying to sort by status
      return order_by_status(table, running_ids) if column == "status"

      return table.order(Arel.sql("COALESCE(rooms.last_session,rooms.created_at) DESC")) if column == "created_at"

      return table.order(Arel.sql("rooms.#{column} #{direction}")) if table.column_names.include?(column)

      return table.order(Arel.sql("#{column} #{direction}")) if column == "users.name"

      table
    end
  end

  # Determines if a user owns a room.
  def owned_by?(user)
    user_id == user&.id
  end

  def shared_users
    User.where(id: shared_access.pluck(:user_id))
  end

  def shared_with?(user)
    return false if user.nil?
    shared_users.include?(user)
  end

  # Determines the invite path for the room.
  def invite_path
    "#{Rails.configuration.relative_url_root}/#{CGI.escape(uid)}"
  end

  # Notify waiting users that a meeting has started.
  def notify_waiting
    ActionCable.server.broadcast("#{uid}_waiting_channel", action: "started")
  end

  # Return table with the running rooms first
  def self.order_by_status(table, ids)
    return table if ids.blank?

    # Get active rooms first
    active_rooms = table.where(bbb_id: ids)

    # Get other rooms sorted by last session date || created at date (whichever is higher)
    inactive_rooms = table.where.not(bbb_id: ids).order("COALESCE(rooms.last_session,rooms.created_at) DESC")

    active_rooms + inactive_rooms
  end

  private

  # Generates a uid for the room and BigBlueButton.
  def setup
    self.uid = random_room_uid
    self.bbb_id = unique_bbb_id
    self.moderator_pw = RandomPassword.generate(length: 12)
    self.attendee_pw = RandomPassword.generate(length: 12)
  end

  # Generates a fully random room uid.
  def random_room_uid
    # 6 character long random string of chars from a..z and 0..9
    full_chunk = SecureRandom.alphanumeric(9).downcase

    [owner.name_chunk, full_chunk[0..2], full_chunk[3..5], full_chunk[6..8]].join("-")
  end

  # Generates a unique bbb_id based on uuid.
  def unique_bbb_id
    loop do
      bbb_id = SecureRandom.alphanumeric(40).downcase
      break bbb_id unless Room.exists?(bbb_id: bbb_id)
    end
  end

  # Before destroying the room, make sure you also destroy the presentation attached
  def destroy_presentation
    presentation.purge if presentation.attached?
  end
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
#
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

module RoomsHelper
  # Helper to generate the path to a Google Calendar event creation
  # It will have its title set as the room name, and the location as the URL to the room
  def google_calendar_path
    "http://calendar.google.com/calendar/r/eventedit?text=#{@room.name}&location=#{request.base_url + request.fullpath}"
  end

  def room_authentication_required
    @settings.get_value("Room Authentication") == "true" &&
      current_user.nil?
  end

  def current_room_exceeds_limit(room)
    # Get how many rooms need to be deleted to reach allowed room number
    limit = @settings.get_value("Room Limit").to_i

    return false if current_user&.has_role?(:admin) || limit == 15

    @diff = current_user.rooms.count - limit
    @diff.positive? && current_user.rooms.pluck(:id).index(room.id) + 1 > limit
  end

  def room_configuration(name)
    @settings.get_value(name)
  end

  def preupload_allowed?
    @settings.get_value("Preupload Presentation") == "true"
  end

  def display_joiner_consent
    # If the require consent setting is checked, then check the room setting, else, set to false
    if recording_consent_required?
      room_setting_with_config("recording")
    else
      false
    end
  end

  # Array of recording formats not to show for public recordings
  def hidden_format_public
    ENV.fetch("HIDDEN_FORMATS_PUBLIC", "").split(",")
  end

  # Returns the total number of visibile rooms for the current user
  def total_room_count(user)
    total = user.rooms.length
    total += user.shared_rooms.length if shared_access_allowed
    total
  end
end

app/views/rooms/cant_create_rooms.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div id="cant-create-room-wrapper" class="d-flex align-content-md-center flex-wrap background h-100 cant-create-room-wrapper">
    <div class="container">
                <div class="row my-7">
                    <div class="col-lg-5 d-none d-lg-flex">
                        <div class="card card-profile h-100">
                            <div class="card-header bg-primary h-50"></div>
                            <div class="card-body text-center">
                              <span class="avatar avatar-xxxl card-profile-img bg-primary"><%= current_user.name.first %></span>
                              <h2 class="mb-3"><%= current_user.name %></h2>
                              <%= link_to edit_user_path(current_user), class: "btn btn-outline-primary mt-2" do %>
                                  <i class="dropdown-icon fas fa-id-card mr-3"></i><%= t("room.no_room.edit_profile") %>
                              <% end %>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-7 col-sm-12">
                        <div class="card h-100">
                            <div class="card-status bg-primary"></div>
                            <div class="card-header cant-create-rooms-title">
                                <h3 class="card-title"><%= t("room.no_room.title") %></h3>
                            </div>
                            <div class="card-body mx-auto col-sm-9 col-12">
                                <p><%= t("room.no_room.description") %></p>
                                <%= form_for(:join_room, url: join_room_path) do |f| %>
                                    <div class="input-icon mb-2">
                                        <span class="input-icon-addon">
                                            <i class="fas fa-link"></i>
                                        </span>
                                        <%= f.text_field :url, class: "form-control", value: "", placeholder: t("room.no_room.placeholder"), required: "" %>
                                    </div>
                                    <div class="mt-4">
                                        <%= f.submit t("room.no_room.go_to"), class:"btn btn-primary btn-block" %>
                                    </div>
                                <% end %>
                            </div>
                            <hr class="mt-0 mb-0">
                            <div class="card-body mx-auto col-sm-9 col-12">
                            <ul class="list-group text-center">
                                <li class="list-group-item active"><%= t("room.no_room.recent_rooms") %></li>
                                <% @recent_rooms.each do |room| %>
                                    <%= link_to room_path(room), class: "list-group-item list-group-item-action dropdown-item"  do %>
                                        <%= room.owner.name + " " + room.name %>
                                    <% end %>
                                <% end %>
                                <% if @recent_rooms.count == 0 %>
                                    <li class="list-group-item"><%= t("room.no_room.no_recent_rooms") %></li>
                                <% end %>
                            </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/join.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<% content_for(:page_desc) { t("room.invitation_description", name: @room.name) } %>

<% access_code_set = @room.access_code.present? %>
<% valid_access_code = access_code_set && @room.access_code == session[:access_code] %>
<% moderator_access_code_set = @room.moderator_access_code.present? && moderator_code_allowed? %>
<% valid_moderator_access_code = valid_moderator_access_code(session[:moderator_access_code]) %>
<% authorized = valid_access_code || valid_moderator_access_code || !access_code_set %>

<%= render 'rooms/components/room_event', render_recordings: authorized do %>
  <% if room_authentication_required %>
    <h2><%= t("administrator.site_settings.authentication.user-info") %></h2>
  <% elsif authorized %>
    <%= form_for room_path(@room), method: :post do |f| %>
      <div class="input-group">
        <%= f.hidden_field(:search, :value => params[:search])%>
        <%= f.hidden_field(:column, :value => params[:column])%>
        <%= f.hidden_field(:direction, :value => params[:direction])%>
        <%= f.text_field :join_name,
            required: true,
            class: "form-control join-form",
            placeholder: t("enter_your_name"),
            value: "#{@name}",
            readonly: !current_user.nil?, 
            autofocus: true,
            maxlength: 99
            %>
        <span class="input-group-append">
          <button id="room-join" type="submit" class="btn btn-primary btn-sm px-7 form-control join-form">
            <%= (!@room_running && @anyone_can_start) ? t("room.start") : t("room.join") %>
          </button>
        </span>
      </div>
      <% if display_joiner_consent %>
        <label class="custom-control custom-checkbox">
          <input id="joiner-consent" type="checkbox" class="custom-control-input" required>
          <h4 class="text-left text-danger mt-4 custom-control-label"><%= t("room.recording_present") %></h4>
        </label>
      <% end %>
    <% end %>
    <% if moderator_access_code_set && !valid_moderator_access_code %>
      <!-- <hr class="mt-2 float-right w-100 moderator-code-hr"> -->
      <label class="moderator-code-label form-label"><%= t("room.optional_moderator_access_code") %></label>
      <%= render "rooms/components/enter_access_code_form", access_code_type: 'moderator' %>
    <% end %>
  <% else %>
    <%= render "rooms/components/enter_access_code_form", access_code_type: 'standard_access' %>
  <% end %>
<% end %>

app/views/rooms/show.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<% exceeds_limit = current_room_exceeds_limit(@room)%>
<% if exceeds_limit%>
  <div class="alert alert-danger alert-dismissible text-center mb-0">
    <%= t("room.room_limit_exceeded", difference: @diff) %>
  </div>
<% end %>
<div class="background pb-1">
  <div class="container">
    <div class="row pt-7 pt-sm-9 mb-7">
      <div class="col-lg-9 col-sm-12">
        <div id="room-title" class="display-3 form-inline <%= 'edit_hover_class' if current_user.main_room != @room %>" data-path="<%= update_settings_path(@room) %>">
           <h1 contenteditable=false id="user-text" class="display-3 text-left mb-3 font-weight-400 text-break"><%= title(@room.name) %></h1>
          <% if current_user.main_room == @room %>
            <a class="disable-click"><i class="fas fa-home align-top home-indicator ml-2"></i></a>
          <% else %>
            <a><i id="edit-room" class="fa fa-edit align-top home-indicator ml-2" data-edit-room="<%= @room.uid %>"></i></a>
          <% end %>
        </div>
        <h4 class="text-left mb-6"><%= @room.sessions %> <%= t("room.sessions") %><% unless hide_recording_tables %> | <%= @recordings.length %> <%= t("room.recordings") %><% end %></h4>
        <% unless exceeds_limit %>
          <label class="form-label"><%= t("room.invite_participants") %></label>
          <div class="row">
            <div class="col-lg-6 col-md-12 mt-2">
              <div class="input-icon invite-link-input">
                <span class="input-icon-addon">
                  <i class="fas fa-link"></i>
                </span>
                <input id="invite-url" type="text" class="form-control w-100" value="<%= request.base_url + @room.invite_path %>" readonly="">
              </div>
            </div>
            <div class="col-lg-6 pr-lg-7 col-md-12 pl-lg-0">
              <div class="row">
                <div class="col-sm-6 mt-2">
                  <button id="copy-invite" class="btn btn-primary btn-block" onclick="copyInvite()">
                    <i class="fas fa-copy mr-1"></i>
                    <%= t("copy") %>
                  </button>
                </div>
                <div class="btn-group-vertical col-sm-6 pl-0 mt-2">
                  <% if @room.access_code.present? %>
                    <input id="copy-code" value="<%= @room.access_code %>" type="hidden">
                    <button id="copy-access" class="btn btn-secondary btn-block" onclick="copyAccess()">
                      <i class="fas fa-copy mr-1"></i>
                      <%= t("room.copy_access") %>
                    </button>
                  <% end %>
                  <% if moderator_code_allowed? && @room.moderator_access_code.present? %>
                    <input id="copy-moderator-code" value="<%= @room.moderator_access_code %>" type="hidden">
                    <button id="copy-moderator-access" class="btn btn-secondary btn-block" onclick="copyAccess('moderator')">
                      <i class="fas fa-copy mr-1"></i>
                      <%= t("room.copy_moderator_access") %>
                    </button>
                  <% end %>
                  <% if Rails.configuration.enable_google_calendar_button %>
                    <a href="<%= google_calendar_path %>" target="__blank" id="schedule" class="btn btn-primary btn-block mt-2">
                      <i class="fas fa-calendar-plus"></i>
                      <%= t("add_to_google_calendar") %>
                    </a>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-lg-3 col-sm-12 force-bottom mt-5">
        <% if @room_running %>
          <%= button_to t("room.join"), room_path(@room), class: "btn btn-primary btn-block start-button float-right", "data-disable": "" %>
        <% else %>
          <% unless exceeds_limit %>
            <%= button_to t("room.start"), start_room_path(@room), class: "btn btn-primary btn-block start-button float-right", "data-disable": "" %>
          <% end %>
        <% end %>
      </div>
    </div>

    <% if total_room_count(current_user) > 5 %>
      <div class="input-icon invite-link-input mb-3">
        <span class="input-icon-addon">
          <i class="fas fa-search"></i>
          </span>
        <input id="room-search" type="text" placeholder="<%= t("room.search") %>" class="form-control w-100" onChange="filterRooms()" onKeyUp="filterRooms()">
        <span id="clear-room-search" class="text-primary" onclick="clearRoomSearch()">
          <i class="fas fa-times"></i>
        </span>
      </div>
    <% end %>

    <div id="room_block_container" class="row mb-5">
      <% if current_user.role.get_permission("can_create_rooms") %>
        <% current_user.ordered_rooms.each do |room| %>
          <div class="col-lg-4 col-md-6 col-sm-12">
            <%= link_to room do %>
              <%= render "rooms/components/room_block", room: room %>
            <% end %>
          </div>
        <% end %>
      <% end %>

      <% if shared_access_allowed %>
        <% current_user.shared_rooms.each do |room| %>
          <div class="col-lg-4 col-md-6 col-sm-12">
            <%= link_to room do %>
              <%= render "rooms/components/shared_room_block", room: room %>
            <% end %>
          </div>
        <% end %>
      <% end %>

      <% if current_user.role.get_permission("can_create_rooms") && !room_limit_exceeded %>
        <%= render "rooms/components/create_room_block"%>
      <% end %>
    </div>
  </div>
</div>

<% unless hide_recording_tables %>
  <%= render "shared/sessions", recordings: @recordings, pagy: @pagy, only_public: false, shared_room: @shared_room, user_recordings: false, title: t("room.recordings")%>
<% end %>

<%= render "shared/modals/delete_room_modal" %>

<%= render "shared/modals/create_room_modal" %>

<% if preupload_allowed? %>
  <%= render "shared/modals/preupload_presentation_modal" %>
<% end %>

<% if shared_access_allowed %>
  <%= render "shared/modals/share_room_modal" %>
  <%= render "shared/modals/remove_access_modal" %>
<% end %>

app/views/rooms/wait.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<%= render 'rooms/components/room_event', render_recordings: true do %>
  <div class="row">
    <div class="col-9">
      <h3><%= t("room.wait.message") %></h3>
      <h4 class="text-muted"><%= t("room.wait.auto") %></h4>
    </div>
    <div class="col-3">
      <div class="loader align-bottom mt-3"></div>
    </div>
  </div>
<% end %>